= Analyse du domaine

== Introduction

Risk est un jeu de conquete du monde, pour trois a six joueurs, chaque joueur doit bouger ses troupes strategiquement pendant son tour s'il veut remporter la partie. Si un joueur remplit la mission qui lui a ete confie au debut du jeu, il gagne la partie.
D’un point de vue fonctionnel, Risk a deux cas d’utilisation (ou fonctionnalités) principaux: la mise en place d’un jeu et jouer un tour.

== Cas d'utilisation principaux

Dans cette section, nous utilisons les Cas d’utilisation efficaces d’Alistar Cockburn pour spécifier les cas d’utilisation principaux de Risk:

1. mise en place du jeu
2. Jouer un tour

== Acteurs

Nous avons considéré deux acteurs, le joueur( de 1 a n joueurs) et l'arbitre qui va reguler le jeu

=== Joueur
Le joueur est celui qui joue une partie. La partie comprend deux a six joueurs, qui sont des adversaires, l’un de l’autre.
Un seul des joueurs commence la partie, l'initiateur.

=== Arbitre
L’arbitre veille au bon déroulement des parties. Il calcule les effets à appliquer en début et fin de tour.

include::uc-mise-place.adoc[leveloffset=+2]


== Conclusion
