

= Description

Entre trois et six joueurs se trouvent pour jouer à Risk.
L'arbitre (Système) prépare et distribue les cartes aux joueurs et les armées selon le nombre de joueur present dans la partie.
Chaque joueur prend une couleur, l'arbitre attribut la position de chaque joueur dans la partir.

= Id: UC-001

= Niveau
* Stratégique.

= Portée

 * Système.

= Priorité
 * Haute.

= Acteurs principaux

1. Les joueurs.
2. L'arbitre.

= Acteurs de soutien

* Aucun pour l'instant

= Parties prenantes et intérêts

* Les autres joureurs.

= Pré-conditions

* Les joueurs sont connectés au jeu.
* Le nombre de joueurs est déterminé.
* Les cartes et les pions sont prêts.


== Post-conditions

=== Condition finale de réussite

* Chaque joueur a une couleur et les régiments qui corréspondent à cette couleur.
* Le tour de chaque joueur est défini.

=== Condition finale d'échec

* Un ou plusieurs joueurs se déconnectent.
* Les régiments de départ ne sont pas distribués à un ou plusieurs joueurs.

=== Garanties minimales

* Aucune

== Événement déclencheur

Les  joueurs se retrouvent et souhaitent s'affronter.

== Scénario nominal

1. L’arbitre initialise le plateau de jeu et place cartes dans la pile.
2. Chaque joueur choisit  une couleur et prend les pions correspondants à cette couleur.
Chaque pion représente un certain nombre dee
régiments, comme indiqué ci-dessous :

* [big]*1* infanterie correspond à [big]*1* régiment.
* [big]*1* cavalerie correspond à [big]*5* régiments.
* [big]*1* artillerie correspond à [big]*10* régiments.

3. L’arbitre distribue les régiments de départ aux joueurs selon le nombre de joueurs :

* A [big]*3* joueurs chacun prend [big]*35* régiments.


* A [big]*4* joueurs chacun prend [big]*30*  régiments.


* A [big]*5*  joueurs chacun prend [big]*25* régiments.


* A [big]*6*  joueurs chacun prend [big]*20*   régiments.

4. L'arbitre définit le tour des joueur (le premier joueur est le joueur qui se connecte en premier et pour le reste des joueurs l’arbitre définit le tour au hasard)

== Extensions


== Variantes


== Fréquence

* Au début du jeu.

== Hypothèses

* Il existe un chemin de communication entre l'arbitre et les joueurs et entre les joueurs.

== Exigences particulières

* Aucun

== Annexes
